<?php

class CategoriesController extends Controller
{
    public function index()
    {
        // TODO: Change the autogenerated stub
    }


    public function insert()
    {

    }

    public function update()
    {

    }

    public function delete()
    {

    }
}